name: ci-fullstack-workflow

# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  schedule:
    - cron: '0 0 * * 0'

  push:
    branches:
      - main

#Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      # Check out the code from the repository.
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up a Node.js environment using the specified node version.
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install the dependencies.
      - name: Install Dependencies
        run: npm install

      # Run the tests.
      - run: 

      # Run the linter.
      - run: 

      # Send a console message at completion.
      - run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."

        
